#!/usr/bin/env bash

set -e

VERSION=$1
if [ "x" = "x$VERSION" ]; then
  echo 'Must provide version to deploy.'
  exit 1
fi

sbt clean
sbt publishLocal
sbt "+ publishLocal"

echo
echo

mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.10/$VERSION/poms/sigopt-spark_2.10.pom" target/scala-2.10
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.10/$VERSION/jars/sigopt-spark_2.10.jar" target/scala-2.10
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.10/$VERSION/srcs/sigopt-spark_2.10-sources.jar" target/scala-2.10
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.10/$VERSION/docs/sigopt-spark_2.10-javadoc.jar" target/scala-2.10
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.11/$VERSION/poms/sigopt-spark_2.11.pom" target/scala-2.11
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.11/$VERSION/jars/sigopt-spark_2.11.jar" target/scala-2.11
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.11/$VERSION/srcs/sigopt-spark_2.11-sources.jar" target/scala-2.11
mv "$HOME/.ivy2/local/com.sigopt/sigopt-spark_2.11/$VERSION/docs/sigopt-spark_2.11-javadoc.jar" target/scala-2.11
declare -a FILES=( \
  "target/scala-2.10/sigopt-spark_2.10-$VERSION.jar" \
  "target/scala-2.10/sigopt-spark_2.10-$VERSION.pom" \
  "target/scala-2.10/sigopt-spark_2.10-${VERSION}-sources.jar" \
  "target/scala-2.10/sigopt-spark_2.10-${VERSION}-javadoc.jar" \
  "target/scala-2.11/sigopt-spark_2.11-$VERSION.jar" \
  "target/scala-2.11/sigopt-spark_2.11-$VERSION.pom" \
  "target/scala-2.11/sigopt-spark_2.11-${VERSION}-sources.jar" \
  "target/scala-2.11/sigopt-spark_2.11-${VERSION}-javadoc.jar" \
)

echo 'Publishing the following files:'
for FILE in ${FILES[@]}; do
  echo "  $FILE"
done
echo

read -s -p "Enter GPG signing passphrase:" GPG_PASSPHRASE
echo
for FILE in ${FILES[@]}; do
  echo "$GPG_PASSPHRASE" | gpg -ab --batch --passphrase-fd 0 "$FILE"
done

echo 'Upload these files to bintray and then publish to Maven Central'
for FILE in ${FILES[@]}; do
  echo "  $FILE"
  echo "  $FILE.asc"
done
